# Generated by Django 5.1.1 on 2024-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('manager_username', models.CharField(max_length=255)),
                ('manager_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
